# Generated by Django 5.2.8 on 2025-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Oficio', 'verbose_name_plural': 'Oficios'},
        ),
        migrations.AlterModelOptions(
            name='reviewanalytics',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='useranalytics',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='reviewanalytics',
            name='score',
            field=models.DecimalField(decimal_places=1, help_text='Puntuación de 1.0 a 5.0 (permite medias estrellas)', max_digits=2),
        ),
        migrations.AddIndex(
            model_name='reviewanalytics',
            index=models.Index(fields=['score'], name='analytics_r_score_e1356f_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewanalytics',
            index=models.Index(fields=['created_at'], name='analytics_r_created_8f0698_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewanalytics',
            index=models.Index(fields=['reviewer'], name='analytics_r_reviewe_93a921_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewanalytics',
            index=models.Index(fields=['reviewed'], name='analytics_r_reviewe_aae44e_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['is_worker'], name='analytics_u_is_work_26c61f_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['created_at'], name='analytics_u_created_456ba2_idx'),
        ),
        migrations.AlterModelTable(
            name='job',
            table='analytics_job',
        ),
        migrations.AlterModelTable(
            name='reviewanalytics',
            table='analytics_review',
        ),
        migrations.AlterModelTable(
            name='useranalytics',
            table='analytics_user',
        ),
    ]
