# Generated by Django 5.2.6 on 2025-11-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_job_options_alter_reviewanalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reviewanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useranalytics',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='reviewanalytics',
            name='analytics_r_reviewe_93a921_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewanalytics',
            name='analytics_r_reviewe_aae44e_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='firebase_key',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewanalytics',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
